### ISSUE TITLE
Traceback message are not complete

### ISSUE THREAD

**Issue by lidall** [marselester/json-log-formatter#17]
Hi,

I am trying to use your package to implement json formatted logs in our system. But I noticed that the traceback messages only contains part of its info. For exmaple, I made my code looking for the undefined module. The actual traceback looks like:

Traceback (most recent call last):
  File "C:\Users\LLIU82\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\LLIU82\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\LLIU82\localtest\test.py", line 9, in <module>
    run_my_stuff()
NameError: name 'run_my_stuff' is not defined

But the log in json looks like:
`{"message": "Got exception on main handler", "time": "2021-01-22T09:22:46.028294", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\LLIU82\\localtest\\test.py\", line 9, in <module>\n    run_my_stuff()\nNameError: name 'run_my_stuff' is not defined"}`

My logging config looks like:

[loggers]
keys=root

[handlers]
keys=console

[formatters]
keys=json

[logger_root]
level=DEBUG
handlers=console

[handler_console]
class=StreamHandler
formatter=json
args=(sys.stdout, )

[formatter_json]
class=json_log_formatter.JSONFormatter

Do we config something wrong? How can I store all my traceback logs in the json?

BR
Lida

**Comment by marselester** [comment]
Hello Lida,

[`JSONFormatter.json_record()`](https://github.com/marselester/json-log-formatter/blob/9ff4cc75760f33b6ab37302ffabc98c68855e9a9/json_log_formatter/__init__.py#L102) calls [`formatException()`](https://docs.python.org/3/library/logging.html#logging.Formatter.formatException) of the standard `logging.Formatter` which in turn calls [`traceback.print_exception()`](https://docs.python.org/3/library/traceback.html#traceback.print_exception).

```python
>>> import traceback
>>> traceback.print_exception(*record.exc_info)
Traceback (most recent call last):
  File "/Users/.../json-log-formatter/tests.py", line 75, in test_exc_info_is_logged
    raise ValueError('something wrong')
NameError: name 'run_my_stuff' is not defined
```

According to the documentation, `print_exception()` output matches what interpreter itself prints when there is an unhandled exception.

> If chain is true (the default), then chained exceptions (the __cause__ or __context__ attributes of the exception) will be printed as well, like the interpreter itself does when printing an unhandled exception. https://docs.python.org/3/library/traceback.html#traceback.print_exception

Maybe the difference between two outputs you've provided is due to the place where the exception was handled (logged). If it's handled earlier, then there will be less information to show.

> My logging config looks like:

Unfortunately I am not familiar with that format. There was a question about Django config, maybe it will help https://github.com/marselester/json-log-formatter/issues/16.
